-- ============================================================================
-- ESQUEMA DE SUPABASE PARA EL ACTUALIZADOR DE FÚTBOL BOLIVIANO
--
-- Ejecutar una sola vez en: Supabase -> SQL Editor -> New query -> Run.
-- Es idempotente: se puede volver a ejecutar sin romper nada.
--
-- Modelo general:
--   ejecuciones            -> una fila por corrida del scraper
--   fuentes                -> catálogo de las 20 fuentes (estado actual)
--   ejecuciones_fuentes    -> cómo le fue a cada fuente en cada corrida
--   tablas                 -> tablas HTML crudas (jsonb, forma variable)
--   posiciones             -> filas de tablas de posiciones ya normalizadas
--   secciones              -> bloques de texto (goleadores, fixture, etc.)
--   noticias               -> archivo acumulado, deduplicado por URL
--   equipos / jugadores    -> catálogo estructurado de Red Uno
--   equipos_estadisticas   -> stats por equipo y por corrida
--   jugadores_estadisticas -> stats por jugador y por corrida
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Corridas
-- ----------------------------------------------------------------------------
create table if not exists public.ejecuciones (
    id                    bigint generated by default as identity primary key,
    generado_en           timestamptz not null unique,
    schema_version        integer,
    zona_horaria          text,
    fuentes_configuradas  integer not null default 0,
    fuentes_correctas     integer not null default 0,
    fuentes_parciales     integer not null default 0,
    fuentes_con_error     integer not null default 0,
    tablas_extraidas      integer not null default 0,
    noticias_extraidas    integer not null default 0,
    equipos_estructurados integer not null default 0,
    creado_en             timestamptz not null default now()
);

comment on table public.ejecuciones is
    'Una fila por ejecución del actualizador. generado_en es la clave de idempotencia.';

create index if not exists ejecuciones_generado_en_idx
    on public.ejecuciones (generado_en desc);

-- ----------------------------------------------------------------------------
-- Catálogo de fuentes
-- ----------------------------------------------------------------------------
create table if not exists public.fuentes (
    id              text primary key,
    nombre          text not null,
    modo            text,
    categoria       text,
    url             text,
    solo_futbol     boolean not null default false,
    habilitada      boolean not null default true,
    actualizado_en  timestamptz not null default now()
);

comment on table public.fuentes is
    'Catálogo de fuentes tal como está en fuentes.json. Se hace upsert en cada corrida.';

create index if not exists fuentes_categoria_idx on public.fuentes (categoria);

-- ----------------------------------------------------------------------------
-- Resultado de cada fuente en cada corrida
-- ----------------------------------------------------------------------------
create table if not exists public.ejecuciones_fuentes (
    id                 bigint generated by default as identity primary key,
    ejecucion_id       bigint not null references public.ejecuciones (id) on delete cascade,
    fuente_id          text   not null references public.fuentes (id) on delete cascade,
    estado             text   not null,
    codigo_http        integer,
    url_final          text,
    titulo_pagina      text,
    actualizado_en     timestamptz,
    ultimo_intento_en  timestamptz,
    duracion_ms        integer,
    cantidad_tablas    integer not null default 0,
    cantidad_noticias  integer not null default 0,
    cantidad_equipos   integer not null default 0,
    datos_desde_cache  boolean not null default false,
    error              text,
    unique (ejecucion_id, fuente_id)
);

comment on column public.ejecuciones_fuentes.datos_desde_cache is
    'true cuando la fuente falló y se conservaron los datos de la corrida anterior.';

create index if not exists ejecuciones_fuentes_fuente_idx
    on public.ejecuciones_fuentes (fuente_id, ejecucion_id desc);
create index if not exists ejecuciones_fuentes_estado_idx
    on public.ejecuciones_fuentes (estado);

-- ----------------------------------------------------------------------------
-- Tablas HTML crudas
-- ----------------------------------------------------------------------------
create table if not exists public.tablas (
    id             bigint generated by default as identity primary key,
    ejecucion_id   bigint not null references public.ejecuciones (id) on delete cascade,
    fuente_id      text   not null references public.fuentes (id) on delete cascade,
    indice         integer not null,
    nombre         text,
    es_posiciones  boolean not null default false,
    columnas       jsonb  not null default '[]'::jsonb,
    filas          jsonb  not null default '[]'::jsonb,
    unique (ejecucion_id, fuente_id, indice)
);

comment on table public.tablas is
    'Tablas HTML tal como se extrajeron. La forma varía por fuente, por eso van en jsonb. '
    'Cuando es_posiciones = true, las filas también están normalizadas en public.posiciones.';

create index if not exists tablas_fuente_idx on public.tablas (fuente_id, ejecucion_id desc);

-- ----------------------------------------------------------------------------
-- Tablas de posiciones normalizadas
-- ----------------------------------------------------------------------------
create table if not exists public.posiciones (
    id             bigint generated by default as identity primary key,
    ejecucion_id   bigint not null references public.ejecuciones (id) on delete cascade,
    fuente_id      text   not null references public.fuentes (id) on delete cascade,
    tabla_indice   integer not null,
    torneo         text,
    pos            integer,
    equipo         text not null,
    pj             integer,
    ganados        integer,
    empatados      integer,
    perdidos       integer,
    goles_favor    integer,
    goles_contra   integer,
    diferencia     integer,
    puntos         integer,
    unique (ejecucion_id, fuente_id, tabla_indice, equipo)
);

comment on table public.posiciones is
    'Filas de tablas de posiciones detectadas automáticamente (columnas tipo Pos/Equipo/Pts).';

create index if not exists posiciones_ejecucion_idx on public.posiciones (ejecucion_id);
create index if not exists posiciones_equipo_idx    on public.posiciones (equipo);
create index if not exists posiciones_torneo_idx    on public.posiciones (fuente_id, torneo);

-- ----------------------------------------------------------------------------
-- Secciones de texto
-- ----------------------------------------------------------------------------
create table if not exists public.secciones (
    id            bigint generated by default as identity primary key,
    ejecucion_id  bigint not null references public.ejecuciones (id) on delete cascade,
    fuente_id     text   not null references public.fuentes (id) on delete cascade,
    orden         integer not null,
    titulo        text,
    contenido     text,
    unique (ejecucion_id, fuente_id, orden)
);

create index if not exists secciones_fuente_idx on public.secciones (fuente_id, ejecucion_id desc);

-- ----------------------------------------------------------------------------
-- Noticias (archivo acumulado)
-- ----------------------------------------------------------------------------
create table if not exists public.noticias (
    id                text primary key,
    fuente_id         text references public.fuentes (id) on delete set null,
    ejecucion_id      bigint references public.ejecuciones (id) on delete set null,
    titulo            text not null,
    url               text not null,
    fecha             timestamptz,
    fecha_texto       text,
    resumen           text,
    vista_primera_en  timestamptz not null default now(),
    vista_ultima_en   timestamptz not null default now()
);

comment on table public.noticias is
    'Archivo histórico de noticias. El id es el sha1 de la URL, así que una noticia que '
    'aparece en varias corridas actualiza vista_ultima_en en vez de duplicarse.';
comment on column public.noticias.fecha is
    'Solo se llena cuando la fuente publica una fecha parseable (ISO 8601). '
    'El texto original siempre queda en fecha_texto.';

create index if not exists noticias_fuente_idx  on public.noticias (fuente_id);
create index if not exists noticias_fecha_idx   on public.noticias (fecha desc nulls last);
create index if not exists noticias_vistas_idx  on public.noticias (vista_ultima_en desc);

-- ----------------------------------------------------------------------------
-- Equipos (Red Uno)
-- ----------------------------------------------------------------------------
create table if not exists public.equipos (
    id              text primary key,
    fuente_id       text references public.fuentes (id) on delete set null,
    nombre          text,
    nombre_corto    text,
    iniciales       text,
    pais            text,
    tipo            text,
    genero          text,
    colores         jsonb,
    metadatos       jsonb,
    actualizado_en  timestamptz not null default now()
);

create index if not exists equipos_nombre_idx on public.equipos (nombre);

-- ----------------------------------------------------------------------------
-- Jugadores (Red Uno)
-- ----------------------------------------------------------------------------
create table if not exists public.jugadores (
    id              text primary key,
    equipo_id       text references public.equipos (id) on delete cascade,
    nombre          text,
    nombre_completo text,
    dorsal          integer,
    posicion_id     integer,
    posicion        text,
    pais            text,
    nacimiento      date,
    edad            integer,
    altura          text,
    peso            text,
    genero          text,
    actualizado_en  timestamptz not null default now()
);

comment on column public.jugadores.posicion is
    'Traducción de posicion_id (1 arquero, 2 defensa, 3 mediocampista, 4 delantero). '
    'Red Uno no publica la leyenda, así que el mapeo es inferido: usar posicion_id ante la duda.';
comment on column public.jugadores.equipo_id is
    'Último equipo en el que se lo vio. Los transferidos aparecen en el plantel de dos '
    'clubes a la vez, así que para saber qué hizo en cada uno hay que mirar '
    'jugadores_estadisticas.equipo_id, que guarda una fila por equipo.';

create index if not exists jugadores_equipo_idx   on public.jugadores (equipo_id);
create index if not exists jugadores_posicion_idx on public.jugadores (posicion_id);

-- ----------------------------------------------------------------------------
-- Estadísticas por equipo y por corrida
-- ----------------------------------------------------------------------------
create table if not exists public.equipos_estadisticas (
    id                  bigint generated by default as identity primary key,
    ejecucion_id        bigint not null references public.ejecuciones (id) on delete cascade,
    equipo_id           text   not null references public.equipos (id) on delete cascade,
    goles               integer,
    asistencias         integer,
    tarjetas_amarillas  integer,
    tarjetas_rojas      integer,
    tiros               integer,
    tiros_al_arco       integer,
    tiros_fuera         integer,
    tiros_al_palo       integer,
    faltas              integer,
    faltas_recibidas    integer,
    corners             integer,
    offsides            integer,
    atajadas            integer,
    robos               integer,
    pases               integer,
    pases_correctos     integer,
    pases_incorrectos   integer,
    resumen_crudo       jsonb,
    unique (ejecucion_id, equipo_id)
);

create index if not exists equipos_estadisticas_equipo_idx
    on public.equipos_estadisticas (equipo_id, ejecucion_id desc);

-- ----------------------------------------------------------------------------
-- Estadísticas por jugador y por corrida
-- ----------------------------------------------------------------------------
create table if not exists public.jugadores_estadisticas (
    id                  bigint generated by default as identity primary key,
    ejecucion_id        bigint not null references public.ejecuciones (id) on delete cascade,
    jugador_id          text   not null references public.jugadores (id) on delete cascade,
    equipo_id           text   not null references public.equipos (id) on delete cascade,
    partidos            integer,
    minutos             integer,
    goles               integer,
    asistencias         integer,
    tarjetas_amarillas  integer,
    tarjetas_rojas      integer,
    tiros               integer,
    tiros_al_arco       integer,
    tiros_fuera         integer,
    tiros_al_palo       integer,
    faltas              integer,
    faltas_recibidas    integer,
    corners             integer,
    offsides            integer,
    robos               integer,
    pases               integer,
    pases_correctos     integer,
    pases_incorrectos   integer,
    resumen_crudo       jsonb,
    -- El equipo va en la clave: un jugador transferido tiene una fila por club
    -- en la misma corrida.
    unique (ejecucion_id, jugador_id, equipo_id)
);

create index if not exists jugadores_estadisticas_jugador_idx
    on public.jugadores_estadisticas (jugador_id, ejecucion_id desc);
create index if not exists jugadores_estadisticas_goles_idx
    on public.jugadores_estadisticas (ejecucion_id, goles desc);

-- ============================================================================
-- VISTAS DE CONVENIENCIA
-- Todas apuntan a la última corrida, que es lo que una app normalmente quiere.
-- ============================================================================

create or replace view public.v_ultima_ejecucion as
select *
from public.ejecuciones
order by generado_en desc
limit 1;

create or replace view public.v_estado_fuentes as
select f.id           as fuente_id,
       f.nombre,
       f.categoria,
       f.url,
       ef.estado,
       ef.codigo_http,
       ef.error,
       ef.datos_desde_cache,
       ef.cantidad_tablas,
       ef.cantidad_noticias,
       ef.cantidad_equipos,
       ef.duracion_ms,
       e.generado_en
from public.ejecuciones_fuentes ef
join public.fuentes     f on f.id = ef.fuente_id
join public.ejecuciones e on e.id = ef.ejecucion_id
where ef.ejecucion_id = (select id from public.v_ultima_ejecucion);

create or replace view public.v_posiciones_actuales as
select p.fuente_id,
       f.nombre as fuente,
       f.categoria,
       p.torneo,
       p.pos,
       p.equipo,
       p.pj,
       p.ganados,
       p.empatados,
       p.perdidos,
       p.goles_favor,
       p.goles_contra,
       p.diferencia,
       p.puntos,
       e.generado_en
from public.posiciones p
join public.fuentes     f on f.id = p.fuente_id
join public.ejecuciones e on e.id = p.ejecucion_id
where p.ejecucion_id = (select id from public.v_ultima_ejecucion);

create or replace view public.v_goleadores as
select j.id       as jugador_id,
       j.nombre_completo,
       j.nombre,
       j.dorsal,
       j.posicion,
       eq.nombre  as equipo,
       je.goles,
       je.asistencias,
       je.partidos,
       je.minutos,
       e.generado_en
from public.jugadores_estadisticas je
join public.jugadores   j  on j.id = je.jugador_id
left join public.equipos eq on eq.id = je.equipo_id
join public.ejecuciones e  on e.id = je.ejecucion_id
where je.ejecucion_id = (select id from public.v_ultima_ejecucion)
  and coalesce(je.goles, 0) > 0
order by je.goles desc, je.asistencias desc nulls last;

create or replace view public.v_noticias_recientes as
select n.id,
       n.titulo,
       n.url,
       n.resumen,
       n.fecha,
       n.fecha_texto,
       n.fuente_id,
       f.nombre as fuente,
       f.categoria,
       n.vista_primera_en,
       n.vista_ultima_en
from public.noticias n
left join public.fuentes f on f.id = n.fuente_id
order by coalesce(n.fecha, n.vista_primera_en) desc;

-- ============================================================================
-- ROW LEVEL SECURITY
--
-- Lectura pública para las claves anon/authenticated; la escritura queda solo
-- para la service_role (que ignora RLS y es la que usa GitHub Actions).
-- ============================================================================

grant usage on schema public to anon, authenticated;

do $$
declare
    t text;
begin
    foreach t in array array[
        'ejecuciones', 'fuentes', 'ejecuciones_fuentes', 'tablas', 'posiciones',
        'secciones', 'noticias', 'equipos', 'jugadores',
        'equipos_estadisticas', 'jugadores_estadisticas'
    ]
    loop
        execute format('alter table public.%I enable row level security', t);
        execute format('drop policy if exists "lectura publica" on public.%I', t);
        execute format(
            'create policy "lectura publica" on public.%I for select to anon, authenticated using (true)',
            t
        );
        execute format('grant select on public.%I to anon, authenticated', t);
    end loop;
end
$$;

grant select on
    public.v_ultima_ejecucion,
    public.v_estado_fuentes,
    public.v_posiciones_actuales,
    public.v_goleadores,
    public.v_noticias_recientes
to anon, authenticated;

-- Las vistas se consultan con los permisos de quien las llama (security_invoker),
-- así que respetan las políticas de arriba en vez de saltárselas.
alter view public.v_ultima_ejecucion     set (security_invoker = on);
alter view public.v_estado_fuentes       set (security_invoker = on);
alter view public.v_posiciones_actuales  set (security_invoker = on);
alter view public.v_goleadores           set (security_invoker = on);
alter view public.v_noticias_recientes   set (security_invoker = on);
